apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 068011494031.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 068011494031.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 612b0acf
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
